os: osx
language: dart
osx_image: xcode12.2
dart_task:
  - test: --platform ios
before_install:
  - cd ..
  - git clone https://github.com/flutter/flutter.git
  - export PATH=`pwd`/flutter/bin:`pwd`/flutter/bin/cache/dart-sdk/bin:$PATH
  - flutter doctor
  - gem install coveralls-lcov
script:
  - cd $TRAVIS_BUILD_DIR
  - flutter pub get
#  - flutter test
  - flutter build ios --debug
cache:
  directories:
    - $HOME/.pub-cache
before_deploy:
  - pushd build/ios/iphoneos
  - mkdir Payload
  - cd Payload
  - ln -s ../Runner.app
  - cd ..
  - zip -r app.ipa Payload
  - popd